name = "DesignStructureMatrix"
uuid = "19401b82-8c43-11e9-36fe-e7e08b9911f1"
authors = ["Otepipi"]
version = "0.1.0"

[deps]
Gadfly = "c91e804a-d5a3-530f-b6f0-dfbca275c004"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
